<a href="https://colab.research.google.com/github/jalanganasamarasekara-del/git_iit_dspl_icw_w2120547/blob/main/W2120547_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import numpy as np
import pandas as pd
import random
import warnings
warnings.filterwarnings('ignore')

In [46]:
df=pd.read_csv('/content/drive/MyDrive/DSPL_ICW_W2120547/Data/Raw/global_currency_2026.csv')

In [47]:
df.head()

,ISO3,country,adm1_name,adm2_name,mkt_name,lat,lon,geo_id,DATES,year,...,l_wage_non_qualified_labour_non_agricultural,c_wage_non_qualified_labour_non_agricultural,inflation_wage_non_qualified_labour_non_agricultural,trust_wage_non_qualified_labour_non_agricultural,o_wage_qualified_labour,h_wage_qualified_labour,l_wage_qualified_labour,c_wage_qualified_labour,inflation_wage_qualified_labour,trust_wage_qualified_labour
0,AFG,Afghanistan,Badakhshan,Argo,Badakhshan,37.04,70.46,gid_370400000704600000,2026-01-01,2026,...,300.00,300.00,0.00,10.0,572.35,588.86,525.15,525.15,4.61,10.0
1,AFG,Afghanistan,Badakhshan,Argo,Badakhshan,37.04,70.46,gid_370400000704600000,2026-02-01,2026,...,281.55,318.65,6.22,10.0,519.77,540.87,504.54,540.87,6.13,10.0
2,AFG,Afghanistan,Badakhshan,Argo,Badakhshan,37.04,70.46,gid_370400000704600000,2026-03-01,2026,...,303.67,316.41,3.31,10.0,541.90,622.21,526.22,622.21,24.44,10.0
3,AFG,Afghanistan,Badakhshan,Argo,Badakhshan,37.04,70.46,gid_370400000704600000,2026-04-01,2026,...,308.42,317.49,5.83,10.0,632.09,650.75,550.96,596.19,11.69,10.0
4,AFG,Afghanistan,Badghis,Jawand,Badghis,35.14,63.73,gid_351400000637300000,2026-01-01,2026,...,262.54,263.76,-12.08,9.9,500.00,504.44,495.56,500.00,-16.67,10.0

In [48]:
df.shape

(12447, 82)

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12447 entries, 0 to 12446
Data columns (total 82 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   ISO3                                                  12447 non-null  object
 1   country                                               12447 non-null  object
 2   adm1_name                                             12447 non-null  object
 3   adm2_name                                             12447 non-null  object
 4   mkt_name                                              12447 non-null  object
 5   lat                                                   12296 non-null  float64
 6   lon                                                   12296 non-null  float64
 7   geo_id                                                12447 non-null  object
 8   DATES                                                 12447 non-null  object
 9   year                                                  12447 non-null  int64
 10  month                                                 12447 non-null  int64
 11  currency                                              12447 non-null  object
 12  batteries                                             0 non-null      float64
 13  candles                                               0 non-null      float64
 14  charcoal                                              0 non-null      float64
 15  exchange_rate_unofficial                              12194 non-null  float64
 16  milling_cost_sorghum                                  23 non-null     float64
 17  milling_cost_wheat                                    9 non-null      float64
 18  soap                                                  0 non-null      float64
 19  wage_non_qualified_labour                             44 non-null     float64
 20  wage_non_qualified_labour_non_agricultural            102 non-null    float64
 21  wage_qualified_labour                                 72 non-null     float64
 22  o_batteries                                           184 non-null    float64
 23  h_batteries                                           184 non-null    float64
 24  l_batteries                                           184 non-null    float64
 25  c_batteries                                           184 non-null    float64
 26  inflation_batteries                                   184 non-null    float64
 27  trust_batteries                                       184 non-null    float64
 28  o_candles                                             184 non-null    float64
 29  h_candles                                             184 non-null    float64
 30  l_candles                                             184 non-null    float64
 31  c_candles                                             184 non-null    float64
 32  inflation_candles                                     184 non-null    float64
 33  trust_candles                                         184 non-null    float64
 34  o_charcoal                                            184 non-null    float64
 35  h_charcoal                                            184 non-null    float64
 36  l_charcoal                                            184 non-null    float64
 37  c_charcoal                                            184 non-null    float64
 38  inflation_charcoal                                    184 non-null    float64
 39  trust_charcoal                                        184 non-null    float64
 40  o_exchange_rate_unofficial                            12447 non-null  float64
 41  h_exchange_rate_unofficial                            12447 non-null  float64
 42  l_exchange_rate_unofficial                            12447 non-null  float64
 43  c_exchange_rate_unofficial                            12447 non-null  float64
 44  inflation_exchange_rate_unofficial                    12447 non-null  float64
 45  trust_exchange_rate_unofficial                        347 non-null    float64
 46  o_milling_cost_sorghum                                156 non-null    float64
 47  h_milling_cost_sorghum                                156 non-null    float64
 48  l_milling_cost_sorghum                                156 non-null    float64
 49  c_milling_cost_sorghum                                156 non-null    float64
 50  inflation_milling_cost_sorghum                        156 non-null    float64
 51  trust_milling_cost_sorghum                            156 non-null    float64
 52  o_milling_cost_wheat                                  75 non-null     float64
 53  h_milling_cost_wheat                                  75 non-null     float64
 54  l_milling_cost_wheat                                  75 non-null     float64
 55  c_milling_cost_wheat                                  75 non-null     float64
 56  inflation_milling_cost_wheat                          75 non-null     float64
 57  trust_milling_cost_wheat                              75 non-null     float64
 58  o_soap                                                184 non-null    float64
 59  h_soap                                                184 non-null    float64
 60  l_soap                                                184 non-null    float64
 61  c_soap                                                184 non-null    float64
 62  inflation_soap                                        184 non-null    float64
 63  trust_soap                                            184 non-null    float64
 64  o_wage_non_qualified_labour                           155 non-null    float64
 65  h_wage_non_qualified_labour                           155 non-null    float64
 66  l_wage_non_qualified_labour                           155 non-null    float64
 67  c_wage_non_qualified_labour                           155 non-null    float64
 68  inflation_wage_non_qualified_labour                   155 non-null    float64
 69  trust_wage_non_qualified_labour                       155 non-null    float64
 70  o_wage_non_qualified_labour_non_agricultural          320 non-null    float64
 71  h_wage_non_qualified_labour_non_agricultural          320 non-null    float64
 72  l_wage_non_qualified_labour_non_agricultural          320 non-null    float64
 73  c_wage_non_qualified_labour_non_agricultural          320 non-null    float64
 74  inflation_wage_non_qualified_labour_non_agricultural  320 non-null    float64
 75  trust_wage_non_qualified_labour_non_agricultural      320 non-null    float64
 76  o_wage_qualified_labour                               239 non-null    float64
 77  h_wage_qualified_labour                               239 non-null    float64
 78  l_wage_qualified_labour                               239 non-null    float64
 79  c_wage_qualified_labour                               239 non-null    float64
 80  inflation_wage_qualified_labour                       239 non-null    float64
 81  trust_wage_qualified_labour                           239 non-null    float64
dtypes: float64(72), int64(2), object(8)
memory usage: 7.8+ MB

In [50]:
df.describe()

,lat,lon,year,month,batteries,candles,charcoal,exchange_rate_unofficial,milling_cost_sorghum,milling_cost_wheat,...,l_wage_non_qualified_labour_non_agricultural,c_wage_non_qualified_labour_non_agricultural,inflation_wage_non_qualified_labour_non_agricultural,trust_wage_non_qualified_labour_non_agricultural,o_wage_qualified_labour,h_wage_qualified_labour,l_wage_qualified_labour,c_wage_qualified_labour,inflation_wage_qualified_labour,trust_wage_qualified_labour
count,12296.000000,12296.000000,12447.0,12447.000000,0.0,0.0,0.0,12194.000000,23.000000,9.000000,...,320.000000,320.000000,320.000000,320.000000,239.000000,239.000000,239.000000,239.000000,239.000000,239.000000
mean,3.086654,41.343419,2026.0,2.496987,NaN,NaN,NaN,4204.432742,3900.369565,4412.036667,...,7836.994875,8841.674906,18.574469,9.349375,6543.912008,6789.257448,6291.637280,6573.796695,-0.859958,9.403766
std,15.933434,36.504701,0.0,1.117176,NaN,NaN,NaN,10017.541240,2349.062135,1048.818605,...,8984.863254,10116.394018,47.736174,1.338483,10836.178629,11360.635852,10218.952839,10890.946372,14.391529,1.400460
min,-26.340000,-90.560000,2026.0,1.000000,NaN,NaN,NaN,5.710000,2000.000000,3000.000000,...,230.600000,247.390000,-53.490000,4.500000,394.210000,492.920000,368.270000,400.000000,-42.860000,4.900000
25%,-7.040000,17.060000,2026.0,1.000000,NaN,NaN,NaN,554.770000,2500.000000,3750.000000,...,297.000000,300.000000,-1.897500,9.275000,599.980000,604.695000,590.675000,600.000000,-8.330000,9.400000
50%,4.580000,36.805000,2026.0,2.000000,NaN,NaN,NaN,1750.230000,3500.000000,4500.000000,...,417.990000,423.585000,0.265000,9.900000,700.000000,708.220000,683.070000,700.000000,-0.750000,10.000000
75%,13.962500,47.840000,2026.0,3.000000,NaN,NaN,NaN,4155.450000,4312.500000,4833.330000,...,14753.357500,16927.472500,27.962500,10.000000,10970.890000,11540.850000,10699.365000,11272.080000,1.985000,10.000000
max,40.900000,140.700000,2026.0,4.000000,NaN,NaN,NaN,89523.010000,11000.000000,6666.670000,...,41912.370000,50108.170000,320.850000,10.000000,53811.070000,56229.240000,45474.660000,50247.410000,67.490000,10.000000

In [51]:
df = df[['DATES', 'country', 'mkt_name', 'currency', 'exchange_rate_unofficial']]

In [52]:
df.head()

        DATES      country    mkt_name currency  exchange_rate_unofficial
0  2026-01-01  Afghanistan  Badakhshan      AFN                     66.00
1  2026-02-01  Afghanistan  Badakhshan      AFN                       NaN
2  2026-03-01  Afghanistan  Badakhshan      AFN                     64.27
3  2026-04-01  Afghanistan  Badakhshan      AFN                       NaN
4  2026-01-01  Afghanistan     Badghis      AFN                     66.00

In [53]:
df.rename(columns={'exchange_rate_unofficial':'Exchange_Rate'}, inplace=True)

In [54]:
df.rename(columns={'country':'Country'}, inplace=True)

In [55]:
df.rename(columns={'DATES':'Dates'}, inplace=True)

In [56]:
df.rename(columns={'mkt_name':'Market Name'}, inplace=True)

In [57]:
df.rename(columns={'currency':'Currency'}, inplace=True)

In [58]:
df.head()

        Dates      Country Market Name Currency  Exchange_Rate
0  2026-01-01  Afghanistan  Badakhshan      AFN          66.00
1  2026-02-01  Afghanistan  Badakhshan      AFN            NaN
2  2026-03-01  Afghanistan  Badakhshan      AFN          64.27
3  2026-04-01  Afghanistan  Badakhshan      AFN            NaN
4  2026-01-01  Afghanistan     Badghis      AFN          66.00

In [59]:
df.isnull().sum()

Dates              0
Country            0
Market Name        0
Currency           0
Exchange_Rate    253
dtype: int64

In [60]:
df.dropna()

,Dates,Country,Market Name,Currency,Exchange_Rate
0,2026-01-01,Afghanistan,Badakhshan,AFN,66.00
2,2026-03-01,Afghanistan,Badakhshan,AFN,64.27
4,2026-01-01,Afghanistan,Badghis,AFN,66.00
5,2026-02-01,Afghanistan,Badghis,AFN,64.07
6,2026-03-01,Afghanistan,Badghis,AFN,64.95
...,...,...,...,...,...
12382,2026-02-01,"Yemen, Rep.",Al Ghaidha,YER,1558.00
12403,2026-02-01,"Yemen, Rep.",Central Ataq - Al Nasib neighbour - Darhim,YER,1558.00
12421,2026-02-01,"Yemen, Rep.",Marib City - Al mujmaa,YER,1561.00
12436,2026-02-01,"Yemen, Rep.",Soqatra (Hudaibo),YER,1559.00
12439,2026-02-01,"Yemen, Rep.",Taiz City,YER,1548.75

In [61]:
df.isnull().sum()

Dates              0
Country            0
Market Name        0
Currency           0
Exchange_Rate    253
dtype: int64

In [63]:
df = df.dropna(subset=['Exchange_Rate'])

In [66]:
df.head()

        Dates      Country Market Name Currency  Exchange_Rate
0  2026-01-01  Afghanistan  Badakhshan      AFN          66.00
2  2026-03-01  Afghanistan  Badakhshan      AFN          64.27
4  2026-01-01  Afghanistan     Badghis      AFN          66.00
5  2026-02-01  Afghanistan     Badghis      AFN          64.07
6  2026-03-01  Afghanistan     Badghis      AFN          64.95

In [67]:
df.dtypes

Dates             object
Country           object
Market Name       object
Currency          object
Exchange_Rate    float64
dtype: object

In [68]:
df['Dates'] = pd.to_datetime(df['Dates'])